language: rust
cache: cargo
sudo: false

rust:
  - nightly
  - beta
  - stable


before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo build --no-default-features
  - cargo test
  - cargo test --no-default-features


matrix:
  allow-failures:
    - rust: nightly
  include:
    - language: rust
      rust: stable
      name: "check wasm32 support"
      install: rustup target add wasm32-unknown-unknown
      script: cargo check --target wasm32-unknown-unknown

