language: rust
cache: cargo
sudo: false

rust:
  - nightly
  - beta
  - stable

before_script:
  - rustup component add rustfmt

script:
  - cargo fmt --all -- --check
  - cargo build
  - cargo build --no-default-features
  - cargo test
  - cargo test --no-default-features