language: rust
cache: cargo
sudo: false

rust:
  - nightly
  - beta
  - stable

before_script:
  - export PATH=$HOME/.cargo/bin:$HOME/.local/bin:$PATH
  - if [[ $(rustup show active-toolchain) == stable* ]]; then rustup component add rustfmt; fi;

script:
  - if [[ $(rustup show active-toolchain) == stable* ]]; then cargo fmt -- --check; fi;
  - cargo build
  - cargo build --no-default-features
  - cargo test
  - cargo test --no-default-features